#ifndef defaults_h
#define defaults_h

#define DEFAULT_XY_STEPS_PER_MM 160.0
#define DEFAULT_XY_MAX_VELOCITY (167.0*60)
#define DEFAULT_XY_MAX_ACCELERATION (3000.0*60*60)
#define DEFAULT_X_MAX_TRAVEL 297.0
#define DEFAULT_Y_MAX_TRAVEL 420.0
#define DEFAULT_STEPPING_INVERT_MASK 0
#define DEFAULT_DIRECTION_INVERT_MASK 0
#define DEFAULT_JUNCTION_DEVIATION 0.010
#define DEFAULT_INVERT_LIMIT_PINS 0
#define DEFAULT_HOMING_ENABLE 0

#endif
